//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apexnet.Messaging.Configuration
{
    
    
    /// <summary>
    /// The ApexnetPushServiceReference Configuration Section.
    /// </summary>
    public partial class ApexnetPushServiceReference : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the ApexnetPushServiceReference Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        internal const string ApexnetPushServiceReferenceSectionName = "apexnetPushServiceReference";
        
        /// <summary>
        /// The XML path of the ApexnetPushServiceReference Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        internal const string ApexnetPushServiceReferenceSectionPath = "ApexnetPushService/apexnetPushServiceReference";
        
        /// <summary>
        /// Gets the ApexnetPushServiceReference instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        public static global::Apexnet.Messaging.Configuration.ApexnetPushServiceReference Instance
        {
            get
            {
                return ((global::Apexnet.Messaging.Configuration.ApexnetPushServiceReference)(global::System.Configuration.ConfigurationManager.GetSection(global::Apexnet.Messaging.Configuration.ApexnetPushServiceReference.ApexnetPushServiceReferenceSectionPath)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Apexnet.Messaging.Configuration.ApexnetPushServiceReference.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::Apexnet.Messaging.Configuration.ApexnetPushServiceReference.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Url Property
        /// <summary>
        /// The XML name of the <see cref="Url"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        internal const string UrlPropertyName = "url";
        
        /// <summary>
        /// Gets or sets the Url.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        [global::System.ComponentModel.DescriptionAttribute("The Url.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Apexnet.Messaging.Configuration.ApexnetPushServiceReference.UrlPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string Url
        {
            get
            {
                return ((string)(base[global::Apexnet.Messaging.Configuration.ApexnetPushServiceReference.UrlPropertyName]));
            }
            set
            {
                base[global::Apexnet.Messaging.Configuration.ApexnetPushServiceReference.UrlPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Apexnet.Messaging.Configuration
{
    
    
    /// <summary>
    /// The ApexnetMailSettingsReference Configuration Section.
    /// </summary>
    public partial class ApexnetMailSettingsReference : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the ApexnetMailSettingsReference Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        internal const string ApexnetMailSettingsReferenceSectionName = "apexnetMailSettingsReference";
        
        /// <summary>
        /// The XML path of the ApexnetMailSettingsReference Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        internal const string ApexnetMailSettingsReferenceSectionPath = "ApexnetMailSettings/apexnetMailSettingsReference";
        
        /// <summary>
        /// Gets the ApexnetMailSettingsReference instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        public static global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference Instance
        {
            get
            {
                return ((global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference)(global::System.Configuration.ConfigurationManager.GetSection(global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference.ApexnetMailSettingsReferenceSectionPath)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Smtp Property
        /// <summary>
        /// The XML name of the <see cref="Smtp"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        internal const string SmtpPropertyName = "smtp";
        
        /// <summary>
        /// Gets or sets the Smtp.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        [global::System.ComponentModel.DescriptionAttribute("The Smtp.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference.SmtpPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Smtp
        {
            get
            {
                return ((string)(base[global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference.SmtpPropertyName]));
            }
            set
            {
                base[global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference.SmtpPropertyName] = value;
            }
        }
        #endregion
        
        #region SmtpUsername Property
        /// <summary>
        /// The XML name of the <see cref="SmtpUsername"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        internal const string SmtpUsernamePropertyName = "smtpUsername";
        
        /// <summary>
        /// Gets or sets the SmtpUsername.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        [global::System.ComponentModel.DescriptionAttribute("The SmtpUsername.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference.SmtpUsernamePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string SmtpUsername
        {
            get
            {
                return ((string)(base[global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference.SmtpUsernamePropertyName]));
            }
            set
            {
                base[global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference.SmtpUsernamePropertyName] = value;
            }
        }
        #endregion
        
        #region SmtpPassword Property
        /// <summary>
        /// The XML name of the <see cref="SmtpPassword"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        internal const string SmtpPasswordPropertyName = "smtpPassword";
        
        /// <summary>
        /// Gets or sets the SmtpPassword.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        [global::System.ComponentModel.DescriptionAttribute("The SmtpPassword.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference.SmtpPasswordPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string SmtpPassword
        {
            get
            {
                return ((string)(base[global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference.SmtpPasswordPropertyName]));
            }
            set
            {
                base[global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference.SmtpPasswordPropertyName] = value;
            }
        }
        #endregion
        
        #region SmtpSsl Property
        /// <summary>
        /// The XML name of the <see cref="SmtpSsl"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        internal const string SmtpSslPropertyName = "smtpSsl";
        
        /// <summary>
        /// Gets or sets the SmtpSsl.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        [global::System.ComponentModel.DescriptionAttribute("The SmtpSsl.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference.SmtpSslPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual bool SmtpSsl
        {
            get
            {
                return ((bool)(base[global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference.SmtpSslPropertyName]));
            }
            set
            {
                base[global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference.SmtpSslPropertyName] = value;
            }
        }
        #endregion
        
        #region SmtpPort Property
        /// <summary>
        /// The XML name of the <see cref="SmtpPort"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        internal const string SmtpPortPropertyName = "smtpPort";
        
        /// <summary>
        /// Gets or sets the SmtpPort.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.5")]
        [global::System.ComponentModel.DescriptionAttribute("The SmtpPort.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference.SmtpPortPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual int SmtpPort
        {
            get
            {
                return ((int)(base[global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference.SmtpPortPropertyName]));
            }
            set
            {
                base[global::Apexnet.Messaging.Configuration.ApexnetMailSettingsReference.SmtpPortPropertyName] = value;
            }
        }
        #endregion
    }
}
